surface_mesh_file_name: "mesh/finger.stl"
volume_mesh_file_name: "mesh/finger.vtk"
# Yes, the collision mesh is an stl.
collision_mesh_file_name: "mesh/finger.stl"
scale: 1
color:
  - 0
  - 1
  - 0
poisson_ratio: 0.25
young_modulus: 1e6
density: 1000

type: "Elastic"
class: "Finger"