target_grasp_angle: 3.14159
grasp_start_horz_offset: 0.9
grasp_start_vert_offset: 0.9
#grasp_start_horz_offset: 1.0
#grasp_start_vert_offset: 1.0

start_pos: [-2.2, -3.45, 2]
#start_pos: [-0.9, 0.7, 0.7] # for flying with vision
#start_pos: [-1.1, -4.7, 2.07] # for flying with mocap
#start_pos: [-2.77, -3.37, 2.07] # for flying with mocap moving
#start_pos: [0.0, -1.7, 1.0] # for flying with vision
#start_pos: [-1.8, -0.7, 1.5] # for flying with vision
#grasp_start_pos: [-1.27, -3.47, 1.9]

start_theta: 0

land_offset: [-1.0, 0.5, 0.0]

# Lateral distance from target when the drone should start closing gripper
# Set this to a very large number to force the grasp state machine to call the gripper close service immediately upon starting the "execute mission" state
#grasp_start_distance: .09 # for vision slow
#grasp_start_distance: .15 # for vision
#grasp_start_distance: .07 # for medkit mocap
#grasp_start_distance: .09 # for medkit mocap
#grasp_start_distance: .12 # for pepsi 1.25m/s mocap
#grasp_start_distance: .04 # for pepsi 2m/s mocap
grasp_start_distance: .1

grasp_attempted_tolerance: .01
#grasp_attempted_tolerance: .9 # for fast mocap

#grasp_start_distance: 0.05 # for moving mocap
#grasp_attempted_tolerance: 0.04 # for moving mocap

drop_position: [1.0, -3.5, 0.0] # for flying with vision
#drop_position: [-.26, -3., 1.9] # mocap

takeoff_offset: 0.4
rise_offset: [0.0, 0.0, 1.0]
open_lengths: [190, 190, 208, 208]
land_threshold: 0.001
dist_threshold: 0.2
average_polynomial_velocity: 0.8
desired_yaw: 0
ground_effect_stop_time: 10.0
control_rate: 30

feedforward_z_acc: 0.0
feedforward_z_acc_duration: 0.3
feedforward_z_acc_delay: 0.4

trajectory_settle_time: 2.0

fixed_grasp_start_point: True
replan_during_grasp_trajectory: False
replan_during_stages: False
require_grasp_confirmation: False
enable_gpio_grasp: True
