target_grasp_angle: 0.0
grasp_start_horz_offset: 2.0
grasp_start_vert_offset: 1.0

fixed_grasp_start_point: True
grasp_start_pos: [-2.0, 0.5, 1.2]
grasp_start_theta: 0.0

land_offset: [-1.0, 0.5, 0.0]

# Lateral distance from target when the drone should start closing gripper
# Set this to a very large number to force the grasp state machine to call the gripper close service immediately upon starting the "execute mission" state
grasp_start_distance: .10

drop_position: [0.0, 1.0, 1.0]
takeoff_offset: 1.0
rise_offset: [0.0, 0.0, 1.0]
open_lengths: [190, 190, 208, 208]
land_threshold: 0.001
dist_threshold: 0.2
grasp_attempted_tolerance: 1
average_polynomial_velocity: 0.8
desired_yaw: 0
ground_effect_stop_time: 10.0
control_rate: 100

trajectory_settle_time: 2.0

replan_during_grasp_trajectory: False
replan_during_stages: False
require_grasp_confirmation: True
enable_gpio_grasp: True
