target_grasp_angle: 0.0
grasp_start_horz_offset: 2.0
grasp_start_vert_offset: 1.0

fixed_grasp_start_point: True
grasp_start_pos: [-2.0, 0.5, 1.0]
grasp_start_theta: 0.0

# Lateral distance from target when the drone should start closing gripper
grasp_start_distance: 0.4

drop_position: [0.0, 1.0, 1.0]
takeoff_offset: 1.0
rise_offset: [0.0, 0.0, 1.0]
open_lengths: [190, 190, 208, 208]
land_threshold: 0.001
dist_threshold: 0.2
grasp_attempted_tolerance: .10
average_polynomial_velocity: 0.8
desired_yaw: 0
ground_effect_stop_time: 10.0
control_rate: 30

trajectory_settle_time: 2.0

replan_during_grasp_trajectory: True
replan_during_stages: True
require_grasp_confirmation: False
enable_gpio_grasp: False
