velocity_prior_var: 3.
angular_velocity_prior_var: 10.
transition_position_prior_cov: .001
transition_rotation_prior_cov: .001
transition_velocity_prior_cov: .001
transition_angular_velocity_prior_cov: .01
smoother_lag: 10.0
