velocity_prior_var: .25
angular_velocity_prior_var: .25
transition_position_prior_cov: .01
transition_rotation_prior_cov: .01
transition_velocity_prior_cov: .01
transition_angular_velocity_prior_cov: .01
smoother_lag: 5.0
