cad_frame_file_name: "$(env HOME)/soft_ws/src/SoftDrone-ROS/softdrone_target_pose_estimator/models/racecar_cad.csv"
noise_bound: 10
cbar2: 1
estimate_scaling: false
rotation_max_iterations: 100
rotatation_gnc_factor: 1.4
rotation_cost_threshold: 0.005

observation_covariance_translation: 0.2
observation_covariance_rotation: 0.05
