timestep: 0.01

objects:
  - name: "Floor"
    config_file: "configs/objects/floor.yaml"
    translation:
      - 0
      - 0
      - 0
    rotation:
      - 0
      - 0
      - 0

  - name: "Target"
    config_file: "configs/objects/target.yaml"
    translation:
      - 0
      - 5
      - 0
    rotation:
      - 0
      - 0
      - 0
  
  - name: "Drone"
    config_file: "configs/objects/drone.yaml"
    translation: 
      - -300
      - 5
      - 0
    rotation:
      - 0
      - 0
      - 0

  - name: "Finger"
    config_file: "configs/fingers/finger.yaml"
    translation: 
      - 300
      - 300
      - 0
    rotation:
      - 0
      - 0
      - 0

