tracker_params:
  agent_topic: "agent_odom"
  target_relative_topic: "dummy/target_relative/pose"
  target_topic: "tracker/target/pose"
  agent_truth_topic: "dummy/agent/pose/truth"
  target_truth_topic: "dummy/target/pose/truth"
