keypoint_detector_params:
  rgb_img_topic: "/camera/color/image_raw"
  model_file_name: "$(env HOME)/KeypointDetectorData/DeployedModels/deployed_keypoint_detector_hardware.pt"
  should_publish_annotated_img: true
  keypoints_topic: "/keypoints_2D"
  annotated_img_topic: "/keypoints_image"
