keypoint_detector_params:
  rgb_img_topic: "/tesse/preproc_img"
  model_file_name: "/home/subella/KeypointDetectorModels/model_hardware_jitted"
  should_publish_annotated_img: true
  keypoints_topic: "/tesse/keypoints"
  annotated_img_topic: "/keypoints_image"
